name: complex-workflow
on: push

jobs:
  ubuntu: 
    name: This is a ubuntu
    runs-on: ubuntu-latest
    steps:
      #- name: This a step in job name ubuntu
      #uses: actions/checkout
      - run: date

  windows: # jobs name: windows
    runs-on: windows-latest
    steps:
    #- name: 
    #uses: actions/checkout@v2
    - run: date
    
  macos: # jobs name: mas OS:
    runs-on: macos-latest
    steps:
    #- name: 
    #uses: actions/checkout@v2
    - run: date
  
  depends: # jobs name: depends
    needs: [ubuntu, windows, macos]
    runs-on: macos-latest
    steps:
    #- name: 
    #uses: actions/checkout@v2
    - run: date 
